name: terra_flutter_bridge
description: Terra Flutter bridge to connect to TerraiOS and TerraAndroid.
version: 0.4.2
homepage: https://github.com/tryterra/terra-flutter

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  plugin:
    platforms:
      android:
        package: co.tryterra.terra_flutter_bridge
        pluginClass: TerraFlutterPlugin
      ios:
        pluginClass: TerraFlutterPlugin


